name: Branch Build

on:
  push:
    branches:
      - '**'

env:
  TZ: 'Europe/Berlin'
  LANG: 'de'
  CONFIGURATION: 'Debug'
  GITEA_SERVER_URL: ${{ gitea.server_url }}

jobs:
  build-test-deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
          cache: false

      - name: Restore dependencies
        run: |
          set -ex
          dotnet restore -v q
          echo "CI_SERVER_HOST=${GITEA_SERVER_URL#https://}" >> "$GITEA_ENV"

      - name: Setup tools
        run: |
          set -ex
          dotnet tool install dotnet-reportgenerator-globaltool --tool-path /dotnet-tools

      - name: Build solution
        shell: bash
        run: |
          set -ex
          shopt -s globstar
          mkdir /artifacts
          dotnet build -c ${CONFIGURATION} --no-restore --nologo
          mv ./**/*.nupkg  /artifacts/
          mv ./**/*.snupkg /artifacts/

      - name: Test solution
        run: |
          set -ex
          dotnet test -c ${CONFIGURATION} --no-build --nologo /p:CoverletOutputFormat=Cobertura
          /dotnet-tools/reportgenerator "-reports:${{ gitea.workspace }}/**/coverage.cobertura.xml" "-targetdir:/reports" "-reportType:TextSummary"
          cat /reports/Summary.txt

      - name: Publish packages
        env:
          BAGET_APIKEY: ${{ secrets.BAGET_APIKEY }}
        run: |
          set -ex
          dotnet nuget push -k ${BAGET_APIKEY} -s https://nuget.am-wd.de/v3/index.json --skip-duplicate /artifacts/*.nupkg
